### ISSUE TITLE
proposal file

### ISSUE THREAD

**Issue by stankur** [stankur/dsci-100-project#8]
For the proposal file, we need to add tables & plots and check the citation, format, etc.

**Comment by svnxxa** [comment]
After editing an existing file in the main branch, do I just make a new branch again to push it? How can I merge?

**Comment by stankur** [comment]
wait but it shouldn't be able to push from the main branch. I think it is not possible to merge from jupyter notebook as well. Maybe the only way is to create a new branch from main in github, and copy the changes from your main branch in Jupyter manually to the new branch

**Comment by svnxxa** [comment]
oh umm, I got it... kinda... let me make a new branch and upload it there first.
